CREATE TABLE jobs (
    job_id INTEGER PRIMARY KEY,
    title VARCHAR(100),
    company VARCHAR(50),
    location VARCHAR(50),
    level VARCHAR(50),
    years_experience_min INTEGER,
    years_experience_max INTEGER,
    url VARCHAR(200)
);

CREATE TABLE skills (
    skill_id INTEGER IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE salary (
    salary_id INTEGER IDENTITY(1,1) PRIMARY KEY,
    job_id INTEGER NOT NULL REFERENCES jobs(job_id),
    amount_min NUMERIC(12,2) NOT NULL,
    amount_max NUMERIC(12,2) NOT NULL,
    time_unit VARCHAR(10) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD'
);

CREATE TABLE job_skills (
    job_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    PRIMARY KEY (job_id, skill_id),
    FOREIGN KEY (job_id) REFERENCES jobs(job_id),
    FOREIGN KEY (skill_id) REFERENCES skills(skill_id)
);

INSERT INTO skills (name) VALUES
('Python'),
('Java'),
('C#'),
('C++'),
('Go'),
('Golang'),
('JavaScript'),
('Rust'),
('Scala'),
('SQL'),
('.NET'),
('ASP.Net'),
('Spring'),
('Django'),
('Flask'),
('React'),
('Vue'),
('Angular'),
('SQL Server'),
('Oracle'),
('PostgreSQL'),
('MySQL'),
('MongoDB'),
('NoSQL'),
('Redshift'),
('BigQuery'),
('Snowflake'),
('Synapse Analytics'),
('Teradata'),
('Aurora'),
('ETL'),
('Airflow'),
('NiFi'),
('Talend'),
('Informatica'),
('SSIS'),
('Glue'),
('dbt'),
('DataStage'),
('Fivetran'),
('Matillion'),
('Azure'),
('Google Cloud Platform'),
('GCP'),
('Amazon Web Services'),
('AWS'),
('S3'),
('Lambda'),
('EMR'),
('RDS'),
('Kinesis'),
('DynamoDB'),
('Athena'),
('EC2'),
('CloudFormation'),
('Data Factory'),
('Databricks'),
('Google Cloud Dataflow'),
('Google Cloud Storage'),
('Google Cloud Pub/Sub'),
('Docker'),
('Kubernetes'),
('Terraform'),
('Azure Pipelines'),
('Puppet'),
('Chef'),
('Ansible'),
('Jenkins'),
('GitLab CI/CD'),
('ADO'),
('Podman'),
('RESTful APIs'),
('GraphQL'),
('HTML'),
('CSS'),
('Git'),
('GitLab'),
('Jira'),
('Confluence'),
('SysML'),
('ORM'),
('Test Management Tools'),
('Agile'),
('DevOps'),
('DevSecOps'),
('Waterfall'),
('CI/CD'),
('Data Warehousing'),
('Hadoop'),
('Spark'),
('Big Data Systems'),
('Business Intelligence'),
('Analytics'),
('Machine Learning');
